name: athr_hr
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter

  cupertino_icons: ^1.0.8



  # Networking & Serialization
  dio: ^5.7.0
  http: ^1.2.2
  shared_preferences: ^2.5.3
  retrofit: ^4.1.0
  logger: ^2.4.0
  pretty_dio_logger: ^1.3.1
  json_annotation: ^4.9.0

  # UI & Utilities
  flutter_screenutil: ^5.9.3
  awesome_snackbar_content: ^0.1.3
  equatable: ^2.0.7
  url_launcher: ^6.3.2


  # Dependency Injection
  injectable: ^2.4.2
  get_it: ^7.7.0

  # State Management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  dartz: ^0.10.1
  file_picker: ^10.3.6
  image_picker: ^1.2.1
  flutter_launcher_icons: ^0.14.4
  intl: ^0.20.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  injectable_generator: ^2.6.1
  retrofit_generator: ^9.1.3
  json_serializable: ^6.9.0
  build_runner: ^2.4.8
  flutter_native_splash: ^2.3.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - translations/ar.json
    - translations/en.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

fonts:
      - family: Cairo
        fonts:
          - asset: assets/fonts/Cairo-ExtraLight.ttf
            weight: 200
          - asset: assets/fonts/Cairo-Light.ttf
            weight: 300
          - asset: assets/fonts/Cairo-Regular.ttf
            weight: 400
          - asset: assets/fonts/Cairo-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/Cairo-Bold.ttf
            weight: 700
          - asset: assets/fonts/Cairo-ExtraBold.ttf
            weight: 800
          - asset: assets/fonts/Cairo-Black.ttf
            weight: 900
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: scaleAspectFit
  fullscreen: true